apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yml
- deployment.yml
- service.yml
- ingress.yml
namespace: default
images:
- name: hello-world-cicd
  newName: sadokf/hello-world-cicd
  newTag: 0.0.87
